### ISSUE TITLE
django-debug-toolbar should not (un)set root logger level

### ISSUE THREAD

**Issue by blueyed** [django-debug-toolbar/django-debug-toolbar#572]
I had a hard time figuring out why the root logger level (`logging.root.level`) was being reset to 0 (NOTSET).

This gets done by DDT:

    logging.root.setLevel(logging.NOTSET)

https://github.com/django-debug-toolbar/django-debug-toolbar/blob/master/debug_toolbar/panels/logging.py#L53

I think that DDT should not change this setting, but only add its handler.
There might be a configuration option for this, but then you could also just configure your root handler accordingly.

**Comment by Zopieux** [comment]
Please see PR #683 and PR #563 for two different (and conflicting) implementations.

**Comment by tim-schilling** [comment]
While they are conflicting, I don't think they are two different implementations of the same thing. #563 exists to prevent memory leaks when running with ```DEBUG=False```.

**Comment by Zopieux** [comment]
Indeed @tim-schilling they do not solve the same issue, so they should be merged somehow. I was just pointing out it was not that simple. :smiley:
