### ISSUE TITLE
Support for callables in SHOW_TOOLBAR_CALLBACK is unavailable in latest stable

### ISSUE THREAD

**Issue by zborboa-google** [django-debug-toolbar/django-debug-toolbar#680]
Change was made in cb428ce6b218f83e45d362d16d1a33143b8e2701.

**Comment by aaugustin** [comment]
The last stable release predates that commit.

**Comment by zborboa-google** [comment]
I'm seeing that as well. https://github.com/django-debug-toolbar/django-debug-toolbar/compare/1.2.2...master
Do you know when the next stable will be released? Thanks

**Comment by zborboa-google** [comment]
Came up with a workaround.

```python
def show_toolbar_callback(request):
    if request.is_ajax():
        return False
    return DEBUG

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': 'my_project.settings.show_toolbar_callback',
}
```
