### ISSUE TITLE
DDT won't display from production server

### ISSUE THREAD

**Issue by flaugher** [django-debug-toolbar/django-debug-toolbar#685]
I'm unable to get the Django Debug Toolbar to display from my production server.  I'm running a Django 1.6 project via Gunicorn 19.1.1 on a Debian 7.8 website behind Nginx 1.2.1.  I've documented my settings and provided more details on what I've done to try and resolve the problem in this [Stackoverflow question](http://stackoverflow.com/questions/28226940/django-debug-toolbar-wont-display-from-production-server).  Briefly, I've used the "Explicit" configuration as described in the DDT documentation.  I've also created a middleware module to ensure that my client IP address gets passed from Nginx to the DDT.  None of this has worked.  As of this morning, my question on SO has had 40 views without so much as a single response.  Can anyone here see what I'm doing wrong?  Thanks!

**Comment by aaugustin** [comment]
The FAQ contains [some troubleshooting tips](http://django-debug-toolbar.readthedocs.org/en/1.2.2/tips.html#the-toolbar-isn-t-displayed) for this problem. I checked the SO question and didn't spot a mistake.

**Comment by tim-schilling** [comment]
Have you considered changing the ```SHOW_TOOLBAR_CALLBACK``` configuration option?

**Comment by aaugustin** [comment]
Without more information, there isn't much we can do here.
