### ISSUE TITLE
Documentation - Mention collectstatic

### ISSUE THREAD

**Issue by orblivion** [django-debug-toolbar/django-debug-toolbar#686]
In the quickstart guide, you mention making sure django's static file serving is working. But for some setups, you also have to run collectstatic for the static files to be visible. You might want to mention that there, unless you think it goes without saying.

**Comment by tim-schilling** [comment]
Are you running your applications with ```DEBUG = False```?

**Comment by tim-schilling** [comment]
In a development environment, you shouldn't have to use ```collectstatic```.

**Comment by orblivion** [comment]
Hmm. Maybe I have my dev environment set up wrong. I didn't put a ton of
time into figuring it all out. But, I am running with debug = True.

Thanks, and sorry for the trouble

**Comment by tim-schilling** [comment]
No problem. You should be able to run your project with ```python manage.py runserver``` then browse out to 127.0.0.1/admin and it should have some sort of css styling without having to run ```collectstatic```.

**Comment by mlissner** [comment]
I ran into this issue too and I suggest we re-open this bug. The problem is that you might be running with `DEBUG = True` in an environment that uses Apache or that otherwise needs to run `collectstatic`. 

I was struggling to get the toolbar working until I opened the browser console for something else and discovered that the files were returning 404's. At that point I ran `collectstatic`, and everything started working.

Can we add something to the docs that says:

> If you are running in an environment that requires that you collect your static assets, run `manage.py collectstatic` after adding `debug_toolbar` to `INSTALLED_APPS`.

That'd go a long ways for people with setups like mine.

**Comment by aaugustin** [comment]
This isn't specific to the toolbar. You'd have the same behavior with any other application that uses static files e.g. django.contrib.admin. We don't want to duplicate Django's documentation -- in this case, the documentation of the staticfiles app.

**Comment by mlissner** [comment]
It's a small thing to add a line about this and it'll save some people lots of time and trouble.

Your call, but in my experience very few Django apps require this step b/c most don't have static resources. At least for me, this wasn't something I was thinking about in the least.

**Comment by aaugustin** [comment]
I'm still reluctant to recommend a step that will be unnecessary for 99,99% of developers, given that runserver serves static files out of the box. There's enough confusion around staticfiles already. If you use a non-standard development setup, you're a little bit on your own.
