### ISSUE TITLE
Introduce warnings of certain DB access patterns using SQL "explain" statement

### ISSUE THREAD

**Issue by mrkschan** [django-debug-toolbar/django-debug-toolbar#688]
Sometimes, certain DB access patterns reported in "EXPLAIN" statement are better to be prevented for scalability reason (e.g. filesort in MySQL). These patterns can be caught during the development phase of a project before the project hitting the mass (especially missing index :). Why can't DjDT add warnings to those patterns?

Using "EXPLAIN" would introduce extra DB queries. Thus, the "auto EXPLAIN" queries are better turned off by default. And, some of the queries are repeating, the "EXPLAIN" results can be cached. When certain DB access patterns that are non-scalable is found, warning message of the SQL statement is inserted to the HTTP response.

Would this feature request be accepted to DjDT? I'm willing to implement this :)

**Comment by aaugustin** [comment]
It's hard to commit to accepting a patch before seeing it ;-) but this looks interesting.

Ideally, the code should be sufficiently modular so warnings can be added for other databases.

**Comment by mrkschan** [comment]
@aaugustin DjDT now does not use django messages framework. Shall I introduce something really new or just patching the SQLPanel?

**Comment by aaugustin** [comment]
I think the logic should be contained within the SQLPanel or a new, standalone panel -- which can be developed externally at first.

**Comment by mrkschan** [comment]
@aaugustin, do you think reusing the SQL tracking logic from SQLPanel is a good idea? https://github.com/mrkschan/django-debug-toolbar/commit/d1d8a422209838f2bdf58a41fa57916038de3449
