### ISSUE TITLE
Could you change the way to examine the INTERNAL_IPS?

### ISSUE THREAD

**Issue by haudoing** [django-debug-toolbar/django-debug-toolbar#690]
Currently it's using REMOTE_ADDR for checking INTERNAL_IPS, but I think it might not be a proper way. Because gunicorn doesn't provide REMOTE_ADDR when using the unix socket. related post [here](https://github.com/benoitc/gunicorn/issues/797). I think the better way is checking "X-Forwarded-For" for now.

**Comment by aaugustin** [comment]
Django used to do that but stopped some releases ago because it was impossible to make it secure in the general case. Write an appropriate middleware to set REMOTE_ADDR to the correct value in your development and production setups.

**Comment by haudoing** [comment]
Hey thanks, I just saw there is some guy on internet explain that using middleware is a better way to do this.

**Comment by JulienPalard** [comment]
In case someone land here, there's another way to get the toolbar in specific contexts:

https://django-debug-toolbar.readthedocs.io/en/latest/configuration.html#show-toolbar-callback
