### ISSUE TITLE
Release version 1.3 (compatible with Django 1.8)

### ISSUE THREAD

**Issue by aaugustin** [django-debug-toolbar/django-debug-toolbar#696]
Let's [roll a release](http://django-debug-toolbar.readthedocs.org/en/1.2.2/contributing.html#making-a-release).

@tim-schilling (or anyone else) Is there anything you would like to commit before making a release?

**Comment by tim-schilling** [comment]
Nope, I can't think of anything. I can do it tomorrow if needed.

**Comment by aaugustin** [comment]
Please do. Thanks!

**Comment by tim-schilling** [comment]
Done, though we missed the translations part of the release. I'm not a maintainer on transifex either. My username there is tim.schilling

**Comment by aaugustin** [comment]
I'll add you to Transifex tonight.

**Comment by aaugustin** [comment]
Done.
