### ISSUE TITLE
Removed In Django 1.9 Warning: url tag from future

### ISSUE THREAD

**Issue by JJZolper** [django-debug-toolbar/django-debug-toolbar#706]
The full warning:

/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/site-packages/django/templatetags/future.py:25: RemovedInDjango19Warning: Loading the `url` tag from the `future` library is deprecated and will be removed in Django 1.9. Use the default `url` tag instead.
  RemovedInDjango19Warning)

I've checked through all my code and I can't find a trace of where I do: {% load url from future %}

Now I've moved onto trying to help third party developers fix their code because I'm getting pretty tired of the warnings popping up. When I ran a search on your code base:

https://github.com/django-debug-toolbar/django-debug-toolbar/search?utf8=%E2%9C%93&q=%7B%25+load+url+from+future+%25%7D

I see that you have used this, this is from way back in Django 1.3 and it is being removed in 1.9 so if you all would, could you please go through clear this all up and let me know when the commit has been pushed so I can pull the updates?

Thanks a lot,

JJ

PS: https://docs.djangoproject.com/en/1.8/releases/1.7/#loading-ssi-and-url-template-tags-from-future-library

**Comment by JJZolper** [comment]
thank you :)

**Comment by shakaran** [comment]
@tim-schilling when will you release this change in pypi? I just see 1.3.0 here https://pypi.python.org/pypi/django-debug-toolbar maybe in 1.3.1? Thanks

**Comment by tim-schilling** [comment]
Yes, this will be in the next version. I'm not sure when that will be exactly though, but it should be in the next month.
