### ISSUE TITLE
Remove "load url from future" in base.html

### ISSUE THREAD

**Issue by km-pg** [django-debug-toolbar/django-debug-toolbar#714]
I'm getting a depreciation warning when using Django 1.8, and I think its coming from the debug toolbar.

RemovedInDjango19Warning: Loading the `url` tag from the `future` library is deprecated and will be removed in Django 1.9. Use the default `url` tag instead.

In base.html, there's {% load url from future %} on the first line which I think can just be removed as long as your ok with not supporting Django versions below 1.5 which isn't getting security updates any more.

**Comment by km-pg** [comment]
Nevermind, this issue was already brought up in issue #706 but hasn't been pushed to pypi yet.

**Comment by lzanuz** [comment]
I'm using django-debug-toolbar==1.3.0 and it still there. Maybe it's time a new release on pypi.
Thanks.

**Comment by tim-schilling** [comment]
I pushed a new version out today.
