### ISSUE TITLE
toolbar not displayed for non-localhost

### ISSUE THREAD

**Issue by lucastan** [django-debug-toolbar/django-debug-toolbar#716]
Hi,

I accessed my site using http://localhost or http://127.0.0.1 and the toolbar is shown.

 I created a host entry in /etc/hosts and accessed through http://xxx.com the toolbar is not shown.

I have DEBUG=False and added xxx.com to INTERNAL_IPS in both cases.

I realised I have to add the IP of xxx.com to INTERNAL_IPS, not the host name itself.

Can I request for a new setting such as DEBUG_HOSTS or to recognise host names in INTERNAL_IPS?

**Comment by tim-schilling** [comment]
You need to have ```DEBUG=True``` in order to have the toolbar display. Another option would be to override ```SHOW_TOOLBAR_CALLBACK```. Here are the [docs](http://django-debug-toolbar.readthedocs.org/en/1.3/configuration.html#debug-toolbar-patch-settings).

**Comment by lucastan** [comment]
Sorry I meant to say DEBUG=True

Anyway it will be good if host names can be recognised in INTERNAL_IPS

I will check out the show toolbar callback

**Comment by tim-schilling** [comment]
I'm not sure I understand your use case. The ```INTERNAL_IPS``` is a whitelisted collection of IP's that send the request to the server that should be allowed to see the debug toolbar. I don't understand why you would need that to support host names.

**Comment by lucastan** [comment]
Sorry i misunderstood internal ips to be server Ips. Turned out to be
client ips instead. You may close this issue

**Comment by tim-schilling** [comment]
Sounds good.
