### ISSUE TITLE
Project not running with django-debug-toolbar

### ISSUE THREAD

**Issue by Vadimkin** [django-debug-toolbar/django-debug-toolbar#717]
Hello!

I use Django 1.8.

Before installing my server running with command «./manage.py runserver» perfectly.

After installing django-debug-toolbar via pip and adding 'debug_toolbar' to INSTALLED_APPS my server not running — after command «./manage.py runserver» I can't get any feedback from terminal. Then I must kill python process for restart app without 'debug_toolbar'.

My settings.py file — https://gist.github.com/Vadimkin/23519410982decb65de2

Also tried to add «DebugToolbarMiddleware» to MIDDLEWARE_CLASSES, create INTERNAL_IPS and install development version, but it doesn't work too :-(

Thanks for help.

**Comment by tim-schilling** [comment]
Have you tried the [Explicit Setup](http://django-debug-toolbar.readthedocs.org/en/latest/installation.html#explicit-setup)?

**Comment by Vadimkin** [comment]
Yes, but it hasn't help for me.

I update `DEBUG_TOOLBAR_PATCH_SETTINGS`, add `'debug_toolbar.middleware.DebugToolbarMiddleware'` to `MIDDLEWARE_CLASSES`, update urls.py, but haven't any effect.

Without `'debug_toolbar'` in `INSTALLED_APPS` (and with `DEBUG_TOOLBAR_PATCH_SETTINGS` and `'debug_toolbar.middleware.DebugToolbarMiddleware'`) project run perfectly and don't show any errors. Toolbar not showing, of course.

Without `django-debug-toolbar` in pip and without `'debug_toolbar'` in `INSTALLED_APPS`, but with `DEBUG_TOOLBAR_PATCH_SETTINGS` and `'debug_toolbar.middleware.DebugToolbarMiddleware'` project not running.

It turns out that Django sees the django-debug-toolbar.

**Comment by tim-schilling** [comment]
When you're using the explicit setup, what exactly is happening? Does the toolbar not show up or does the development web server not start up?

**Comment by Vadimkin** [comment]
Development web server not start up.

**Comment by tim-schilling** [comment]
I would try removing your apps and non-default middlewares one by one until you find which one is conflicting with it. Then investigate why it's breaking when runserver is run.

**Comment by Vadimkin** [comment]
Only with 'django.contrib.staticfiles' and 'debug_toolbar' in INSTALLED_APPS and 'django.contrib.sessions.middleware.SessionMiddleware' in MIDDLEWARE_CLASSES server not running too.

Solve, that worked for me: delete all virtual env and then reinstall all dependencies.

Thank for you help!
