### ISSUE TITLE
Cache panel does not update for per-view level caching

### ISSUE THREAD

**Issue by ybendana** [django-debug-toolbar/django-debug-toolbar#718]
I'm using the toolbar 1.3 and Django 1.8.2.  The toolbar displays fine and the SQL, Time, Headers, Request, Static Files, Templates panels all update but the Cache panel stays fixed at 0 calls even though it's activated.  I've tried it using the LocMemCache and Memcached with same result.  I'm using the explicit setup with DEBUG_TOOLBAR_PATCH_SETTINGS = False.

Here are my Middleware classes:

MIDDLEWARE_CLASSES = (
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.RemoteUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
)

In my urls I have:

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

Is there anything else I'm missing to get the panel to update?

**Comment by ybendana** [comment]
I also tried moving the DebugToolbarMiddleware position in the list but it didn't have any effect.

**Comment by tim-schilling** [comment]
I noticed you didn't include the ```INSTALLED_APPS``` setting. Do you have ```'debug_toolbar'``` included in it?

**Comment by ybendana** [comment]
Yes, I have it set in there.  The toolbar displays fine and the rest of the
panels work, so this problem seems to be Cache specific.  This is the rest
of my config:

DEBUG_TOOLBAR_PATCH_SETTINGS = False
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_COLLAPSED': True,
}
INTERNAL_IPS = ('127.0.0.1', '::1', '10.0.0.49')

**Comment by ybendana** [comment]
I also get the same result when I run my app in the Django test server or in Apache.

**Comment by tim-schilling** [comment]
Where are your calls to the cache occurring? In the view or the middleware?

**Comment by ybendana** [comment]
I'm actually not explicitly calling anything, but caching the whole site to test it out.  Does the panel only display low-level cache API calls?

**Comment by tim-schilling** [comment]
Seems to be that way. I was able to reproduce this.
