### ISSUE TITLE
debug_toolbar must be after django.contrib.admin in INSTALLED_APPS

### ISSUE THREAD

**Issue by gavinwahl** [django-debug-toolbar/django-debug-toolbar#723]
If debug_toolbar is loaded before django.contrib.admin, visiting `/admin/` fails with:

```
NoReverseMatch: Reverse for 'app_list' with arguments '()' and keyword arguments '{'app_label': u'filer'}' not found. 0 pattern(s) tried: []
```

This is because of the way admin registration and debug toolbar url monkeypatching work. If debug toolbar patches the urls before admin has had a chance to autoload, admin won't register any urls. If debug toolbar patches after admin, everything is fine.

Is there any way to fix this or do we just have to document the ordering restriction?

**Comment by aaugustin** [comment]
That's one of the many cases where implicit setup is a bit too magical. We should recommend the explicit setup instead.

**Comment by aaugustin** [comment]
I tweaked the wording in 833147237454a908ab2f83b4b976853de3194a86.
