### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'write' of null" from DDT's jquery.js:5523

### ISSUE THREAD

**Issue by mathuin** [django-debug-toolbar/django-debug-toolbar#726]
https://django-debug-toolbar.readthedocs.org/en/1.3.2/tips.html#the-toolbar-isn-t-displayed

> The Debug Toolbar will only display when DEBUG = True in your project’s settings. It will also only
> display if the mimetype of the response is either text/html or application/xhtml+xml and contains a
> closing </body> tag.
> 
> Be aware of middleware ordering and other middleware that may intercept requests and return
> responses. Putting the debug toolbar middleware after the Flatpage middleware, for example, means > the toolbar will not show up on flatpages.

I work on the [Protein Geometry Database](https://github.com/osuosl/pgd) which is a Django app used by researchers who study proteins.  Some pages will display the DDT, but one in particular for which I had wanted to use the tool does not.

I installed the DDT app by checking out the develop branch of the PGD, adding django-debug-toolbar to requirements.txt, adding debug-toolbar to the INSTALLED_APPS, and adding the code found [here](http://dancarroll.org/blog/2011/01/debugging-django-dev-server/) so INTERNAL_IPS could be set to `glob_list(['*.*.*.*'])`.

I used `./dev-setup.sh` to build the Docker containers for the PGD, then started the container with `docker-compose run --service-ports web bash`.  Once I was in the container, I populated the database with `python manage.py loaddata pgd_core` and then started the web server with `DEBUG=True python manage.py runserver --insecure 0.0.0.0:8000`.  When I visited the URL `http://localhost:8000/` with Chrome, the DDT was visible.  When I clicked on the new search link, the DDT was still there.  However, when I submitted the default search, the DDT did not appear.  I hit F12 to bring up the Chrome Dev Tools, and I saw the following error:  `Uncaught TypeError: Cannot read property 'write' of null`.  The error occurred on line 5523 in the jquery.js downloaded by DDT -- the PGD uses jQuery 1.4.1 at the moment, DDT uses version 2.1.4 from axis.googleapis.com.  Here are the lines around line 5523:

```javascript
    /**
 * Try to determine the default display value of an element
 * @param {String} nodeName
 */
    function defaultDisplay(nodeName) {
        var doc = document, 
        display = elemdisplay[nodeName];
        
        if (!display) {
            display = actualDisplay(nodeName, doc);

            // If the simple way fails, read from inside an iframe
            if (display === "none" || !display) {

                // Use the already-created iframe if possible
                iframe = (iframe || jQuery("<iframe frameborder='0' width='0' height='0'/>")).appendTo(doc.documentElement);

                // Always write a new HTML skeleton so Webkit and Firefox don't choke on reuse
                doc = iframe[0].contentDocument;

                // Support: IE
                doc.write();
                doc.close();
                
                display = actualDisplay(nodeName, doc);
                iframe.detach();
            }

            // Store the correct default display
            elemdisplay[nodeName] = display;
        }
        
        return display;
    }
```

Line 5523 is the line that contains `doc.write();`.  I do not know JavaScript, so I'm not sure if it's a bug in jQuery or a bug in DDT.

Let me know if you need any more information.  The problem can be reproduced with the instructions included above.

**Comment by tim-schilling** [comment]
Have you tried reproducing this in a smaller project? You should also include the stacktrace if you can.

**Comment by tim-schilling** [comment]
Closing this due to lack of response.
