### ISSUE TITLE
your tests are installed by setup.py

### ISSUE THREAD

**Issue by anentropic** [django-debug-toolbar/django-debug-toolbar#729]
...which pollutes the global namespace

I wanted to have a top-level `tests` directory in my project code but I've found several 3rd party packages accidentally install their own `tests` package, so when I `import tests` I get the one from eg django-debug-toolbar.

the problem seems to be this:

```
packages=find_packages(exclude=('tests.*', 'tests', 'example')),
include_package_data=True,
```

the first line looks like it excludes the tests, but something is causing them to be added still - not very clear from the setuptools docs but I believe it's due to the second line above. I fixed another package by adding the line:

```
exclude_package_data={'': ['tests.*', 'tests', 'example']},
```

**Comment by tim-schilling** [comment]
How are you installing the toolbar? I can't reproduce it.

**Comment by anentropic** [comment]
originally via `pip install`

we are using v1.2.1, which has installed as a wheel

```
$ cat /Users/anentropic/.virtualenvs/env/lib/python2.7/site-packages/django_debug_toolbar-1.2.1.dist-info/top_level.txt
tests
debug_toolbar
```

similarly all the `tests/` files can be seen in `/Users/anentropic/.virtualenvs/env/lib/python2.7/site-packages/django_debug_toolbar-1.2.1.dist-info/RECORD`

**Comment by aaugustin** [comment]
1.2.1 is quite old — and already was when this bug was filed.

This problem doesn't appear to exist in the latest version.

     % ls -r $VIRTUAL_ENV/lib/python3.4/site-packages/debug_toolbar | grep test

Please comment if you can reproduce on 1.4.
