### ISSUE TITLE
DDT's cache stats hooks prevent cache.clear() working correctly

### ISSUE THREAD

**Issue by andrewhayes1979** [django-debug-toolbar/django-debug-toolbar#732]
Using:
* Django 1.8.2
* DDT 1.3.0
* memcached backend installed as *'default'* in the *CACHES* setting

I have a link in the admin that calls a naked *cache.clear()* call to reset the *'default'* cache back to empty.

If DDT is not installed/activated (middleware is not present), this works fine.  The *clear()* call is routed through to *django.core.cache.backends.memcached.MemcachedCache.clear()*, as expected.

If DDT is installed, DDT installs stats hooks into the cache in order to capture cache call information...this is installed in the *process_request()* of the middleware.

The call to cache.clear() now gets routed through *django.core.cache.backends.base.BaseCache.clear()*, whereby a *NotImplemented* exception is raised

__DDT is therefore not correctly routing calls to the cache through to the configured backend under all circumstances when it's hooks are installed.__

**Comment by tim-schilling** [comment]
This was fixed by #712 and is in in version 1.3.2.
