### ISSUE TITLE
The "compat" templatetag library collides with other apps

### ISSUE THREAD

**Issue by kezabelle** [django-debug-toolbar/django-debug-toolbar#734]
[django-imagekit](https://github.com/matthewwithanm/django-imagekit) has shipped a `compat` file in it's own templatetags [since 2012](https://github.com/matthewwithanm/django-imagekit/commits/develop/imagekit/templatetags/compat.py). It isn't actually exposed as a template library, though.

The introduction of `debug_toolbar.templatetags.compat` in 5a9bd46f8624320346d829687d3709b0a9beb580 means that there is now an order of precedence in INSTALLED_APPS issue; given:
```
INSTALLED_APPS = (
    'debug_toolbar',
    'imagekit',
)
```
everything is fine.

Swap those values around so that `imagekit` comes first, and debug_toolbar causes:

```
'compat' is not a valid tag library: Template library imagekit.templatetags.compat does not have a variable named 'register'
```

It would seem prudent to me to have the `compat` module namespaced as `debugtoolbar_compat` or such in templates.

**Comment by aaugustin** [comment]
Yes, this is a sensible improvement.

**Comment by philippeluickx** [comment]
+1

**Comment by aaugustin** [comment]
If someone feels like putting together a pull request, the patch shouldn't be too hard.

**Comment by tim-schilling** [comment]
I'll get this done tomorrow.
