### ISSUE TITLE
my page always show '200: OK'

### ISSUE THREAD

**Issue by hongqi** [django-debug-toolbar/django-debug-toolbar#737]
hi, my page always show '200: OK' not the debug info.
i debug the js code:
![aaa](https://cloud.githubusercontent.com/assets/3354923/9108901/fccb365c-3c63-11e5-9b94-b971662f5443.png)

always be in fail()
but the response status is 200

**Comment by tim-schilling** [comment]
Can you include more details?

**Comment by hongqi** [comment]
ok.
page show is:![aaaa](https://cloud.githubusercontent.com/assets/3354923/9127445/cdfdab36-3ced-11e5-877b-0cf9f11d5658.png)
the request is:
![bb](https://cloud.githubusercontent.com/assets/3354923/9127633/32e106b8-3cf0-11e5-951b-ae7a6530253e.png)

**Comment by tim-schilling** [comment]
Sorry I should have been more clear. Could you include the full stacktrace?

**Comment by hongqi** [comment]
thank you for your reply.
this problem has little effect on my development. so I will solve it myself. thanks.
