### ISSUE TITLE
Django 1.9: django.template.base.Library has moved to django.template.library.Library

### ISSUE THREAD

**Issue by Naddiseo** [django-debug-toolbar/django-debug-toolbar#739]
Using current master causes an error:
Invalid template library specified. ImportError raised when trying to load  debug_toolbar.templatetags.compat': cannot import name 'Library'

I think it was caused by: https://github.com/django/django/commit/655f52491505932ef04264de2bce21a03f3a7cd0

**Comment by tim-schilling** [comment]
Unless @aaugustin thinks differently, I'm inclined to leave this as is until 1.9's alpha release on Sept 21.

**Comment by aaugustin** [comment]
The correct import is `from django.template import Library`, it should work in all versions.

**Comment by aaugustin** [comment]
Fixed in 3480a91.
