### ISSUE TITLE
Is django-debug-toolbar thread safe?

### ISSUE THREAD

**Issue by nitely** [django-debug-toolbar/django-debug-toolbar#740]
I'm probably missing something, but after reviewing the [cache code](https://github.com/django-debug-toolbar/django-debug-toolbar/blob/master/debug_toolbar/panels/cache.py), I'm not sure it is thread safe.

It seems a request could be adding its cache results in to another request that's taking place at the same time.

I'm also not sure how `enable_instrumentation/disable_instrumentation` is suppose to help here, since all threads share the same global (cache) object, so calling one or the other would affect all threads, AFAIK.

**Comment by tim-schilling** [comment]
You're correct. The cache panel is not thread safe. I removed that comment, though I shouldn't have.
