### ISSUE TITLE
IndexError at /admin/sql-explorer/play/ when trying to use wildcards

### ISSUE THREAD

**Issue by kopite** [django-debug-toolbar/django-debug-toolbar#745]
I'm using django-sql-explorer on a project locally. 

Everything works fine until I try and do wildcards e.g 

WHERE test Like "%test%"

I get the following error:
IndexError at /admin/sql-explorer/play/

tuple index out of range

Request Method: 	POST
Request URL: 	http://localhost:8000/admin/sql-explorer/play/
Django Version: 	1.8.4
Exception Type: 	IndexError
Exception Value: 	

tuple index out of range

**Comment by tim-schilling** [comment]
Are you using mysql?

**Comment by kopite** [comment]
Postgres

When i disable debug toolbar the command works perfectly.

**Comment by tim-schilling** [comment]
Thanks, closing as duplicate of #705.
