### ISSUE TITLE
Data for this panel isn't available anymore. Please reload the page and retry.

### ISSUE THREAD

**Issue by srus** [django-debug-toolbar/django-debug-toolbar#750]
Hello, I'm getting the following message in some pages: 

**Data for this panel isn't available anymore. Please reload the page and retry.**

I tried updating to the latest version (1.3.2), but still get the same message. It's really strange that for some pages works fine and for others not. Any ideas?

Thanks

**Comment by tim-schilling** [comment]
Is runserver restarting between loading the initial page and using the
toolbar?

**Comment by srus** [comment]
No, it isn't. For example in the home page the toolbar doesn't work. So if after fully loading the page I click the icon to show the toolbar and then click for example in the SQL tab, I can only see 1 request made in the runserver logs. See below the latest 2 requests I get in the runserver logs:

```
"GET /static/images/favicon.ico HTTP/1.1" 200 8348
"GET /__debug__/render_panel/?store_id=dc4583336c2a44aa82c51a0536048b62&panel_id=SQLPanel HTTP/1.1" 200 89
```

**Comment by srus** [comment]
Here you can see the logs I get in a page where the toolbar works fine:
```
"GET /__debug__/render_panel/?store_id=f49ad04e543c4ece912bcdb2d50885b2&panel_id=SQLPanel HTTP/1.1" 200 141066
"GET /static/toolbar/debug_toolbar/js/toolbar.sql.js?_=1442403893082 HTTP/1.1" 200 353
```

**Comment by tim-schilling** [comment]
I'll set if I can reproduce it, but I'll likely need more information about
your project and view.

**Comment by srus** [comment]
Maybe some missing static resource is affecting the toolbar? It's a bit weird, because sometimes it doesn't work in the pages where it used to work fine, but after some reloadings, then it works again.

**Comment by tim-schilling** [comment]
It'd be very helpful if you could create a small sample project that was having the same issue.

**Comment by srus** [comment]
I don't think I can replicate the same environment I have in the current project, since it is a bit complex and big. I guess it's something related to the front-end, since I can open Debug Toolbar, and even works fine in some pages. Although sometimes it doesn't work in those same pages...

**Comment by aaugustin** [comment]
The toolbar keeps track of recent queries where it was inserted, by default the last 10. If you make more than 10 queries where the toolbar is inserted between the initial page load and the moment you open the panel, that would explain the behavior you're seeing.

Increasing RESULTS_CACHE_SIZE may help. See
http://django-debug-toolbar.readthedocs.org/en/latest/configuration.html#debug-toolbar-config.

**Comment by srus** [comment]
@aaugustin Forgot to say thanks. Increasing RESULTS_CACHE_SIZE to 100 solved the problem.

**Comment by gam-phon** [comment]
Yes. Increasing RESULTS_CACHE_SIZE solve my problem also.

**Comment by philgyford** [comment]
For anyone else coming to this, for whom increasing `RESULTS_CACHE_SIZE` doesn't work...

I'm using gunicorn and had its `NUM_WORKERS` set to 1. Increasing it to 2 (or more) fixed this problem.

**Comment by grafa** [comment]
@philgyford thank you very much. Works! (the `NUM_WORKERS`)

**Comment by bmoe872** [comment]
I have done all of the above, and I am still getting this same error message. I am using uWSGI, and increased the number of workers to 2. I also increased the RESULTS_CACHE_SIZE to 100. (I've also tried much higher values)

I'm using Django 1.11.3. 
I am able to see the SQL panel is trying to get ~742queries, but I would like to see what these are.

**Comment by ajostergaard** [comment]
I had this problem BECAUSE I had more than one worker, a worker without knowledge of my history was getting the requests - hence I tried `RENDER_PANELS=True` but that had no effect.

All my debug-toolbar issues went away when I switched to `gunicorn --workers 1` and increased RESULTS_CACHE_SIZE to a more sensible value. :)

**Comment by marangonico** [comment]
I just came across this problem and solved flushing the redis cache ("redis-cli flushall").

**Comment by tutuca** [comment]
I'm running into this issue with the development server (`manage.py runserver`) and no refresh in-between.

**Comment by cfra** [comment]
In my case, running development with Uvicorn so we have a proper ASGI server, it seemed the auto-detection described in the documentation for `RENDER_PANELS` did not work.

Adding the following to my development settings fixed the problem described in this ticket:

```python
DEBUG_TOOLBAR_CONFIG = {
    "RENDER_PANELS": False,
}
```

**Comment by tim-schilling** [comment]
@cfra would you have time to create a reproducible example? It would really help the effort to debug this.

**Comment by cfra** [comment]
@tim-schilling thank you for your inquiry.

Upon further investigation my previous comment seems to be incorrect:

I actually needed to increase `RESULTS_CACHE_SIZE` in this setup, same as some previous comments suggest, to make the panels work.

Apparently, in my setup, for some reason the debug toolbar settings are only taking effect upon a server restart, not on a worker reload.

I was not aware of this behavior while testing different options and seem to have come to the wrong conclusion because of this, as I was running with settings differing from those I was expecting.

Sorry for the noise.

**Comment by tim-schilling** [comment]
Thank you for following up! I wonder if that's due to our caching of settings? It may be worth a separate issue.
