### ISSUE TITLE
KeyError => +active

### ISSUE THREAD

**Issue by paulocheque** [django-debug-toolbar/django-debug-toolbar#761]
I dont know if there is conflict with Jquery or something like that, because I am facing this error just in my landing page.

Because some JS error, the url is ending with an extra `+active` word.

http://localhost:8000/__debug__/render_panel/?store_id=3d4f12bf90ad4a838d4afb6fc630f283&panel_id=SQLPanel+active 

Failed to load resource: the server responded with a status of 500 

![screen shot 2015-10-06 at 1 07 50 am](https://cloud.githubusercontent.com/assets/94350/10299941/beac8294-6bc6-11e5-9a48-781b13f5e34a.png)

If I ran `http://localhost:8000/__debug__/render_panel/?store_id=3d4f12bf90ad4a838d4afb6fc630f283&panel_id=SQLPanel` the toolbar is working.

![screen shot 2015-10-06 at 1 11 35 am](https://cloud.githubusercontent.com/assets/94350/10299986/3ea2661c-6bc7-11e5-8496-c9bb7cf0911c.png)

Any ideas? Thanks in advance!

DTB Version 1.3.2
Django 1.8

**Comment by gabn88** [comment]
+1, did you find out?

**Comment by gabn88** [comment]
Did you use bootstrap?

**Comment by gabn88** [comment]
I used Ionic (just for testing) and that was the culprit. It add an 'activated' class name to the clicked object. (that is how they test if something is clicked/tapped)

**Comment by aaugustin** [comment]
I don't want to introduce complexity in the debug toolbar to work around JS bugs. You can't mangle URLs and expect the code that responds to these URLs to keep working!

**Comment by gabn88** [comment]
Just for completeness, it is not a mangling with URLS, only with classes on a <a> tag, which *should* not break things.

**Comment by noamvaza** [comment]
We had the same error, a scrolling js function acts on all the document made changes in the toolbar links.

Search your JS for something like:

`$('a[href^="#"]').on('click', function (e) {`

Change the jquery to filter the element in a smaller div.

`$('#YOUR_DIV_ID a[href^="#"]').on('click', function (e) {`
