### ISSUE TITLE
Wrong version gets installed from Pypi

### ISSUE THREAD

**Issue by shaung** [django-debug-toolbar/django-debug-toolbar#765]
When performing
```
pip install django-debug-toolbar==1.4
```
It actually installs `1.3.2`.

Installing from source installs the correct version:
```
pip install --no-use-wheel django-debug-toolbar==1.4
```

**Comment by aaugustin** [comment]
PyPI provides both a .tar.gz and a universal wheel for 1.3.2 and 1.4.

Aside from the version number, file names are identical.

- https://pypi.python.org/pypi/django-debug-toolbar/1.3.2
- https://pypi.python.org/pypi/django-debug-toolbar/1.4

I cannot replicate this locally.

Can you try upgrading to the latest version of pip and see if this still happens?

Can you confirm you're using pypi.python.org and not another repository like devpi?
