### ISSUE TITLE
Upgarding to 1.4 is buggy

### ISSUE THREAD

**Issue by andrewfam** [django-debug-toolbar/django-debug-toolbar#777]
I upgraded to 1.4 from 1.2 and the toolbar doesn't appear in my pages but appears in the 404 and admin.
Downgrading to 1.3 works

**Comment by aaugustin** [comment]
I understand what you're saying, but since I don't have access to your pages, there's nothing I can with this report.

Please provide at least one of the following:

- stack trace (JS or Python)
- reproduction instructions
- suggested improvement

**Comment by andrewfam** [comment]
Hey sorry,

These are my settings. No stacktrace or js errors when checking google chrome

SHARED_INT_APPS = (
    'clients',
    'dashboard',
    'feedback',
    'homepage',
    'imp_settings',
    'reports',
)

TENANT_DJANGO_APPS = (
    'django.contrib.contenttypes',
    'suit',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.auth'
)

TENANT_EXT_APPS = (
    'allauth',
    'allauth.account',
    'debug_toolbar',
)

TENANT_INT_APPS =(
    'bookings',
    'campaigns',
    'cbuilder',
    'hotels',
    'req_groups',
    'sf_settings',
    'userprofiles',
)

TENANT_APPS = TENANT_DJANGO_APPS + TENANT_EXT_APPS + TENANT_INT_APPS
SHARED_APPS = SHARED_DJANGO_APPS + SHARED_EXT_APPS + SHARED_INT_APPS

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

TENANT_MODEL = "clients.Client"

DATABASE_ROUTERS = (
    'tenant_schemas.routers.TenantSyncRouter',
)

LOGIN_REDIRECT_URL = '/dashboard/'

CRISPY_TEMPLATE_PACK = 'bootstrap3'

MIDDLEWARE_CLASSES = (
    'tenant_schemas.middleware.TenantMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware'
)

DEBUG = TEMPLATES[0]['OPTIONS']['debug'] = True

INTERNAL_IPS = '127.0.0.1'

def show_toolbar(request):
    return True
SHOW_TOOLBAR_CALLBACK = show_toolbar

**Comment by aaugustin** [comment]
I see a reference to bootstrap above. This may have been a duplicated of #742.
