### ISSUE TITLE
Django Admin actions are not profiled.

### ISSUE THREAD

**Issue by TravisDart** [django-debug-toolbar/django-debug-toolbar#782]
I want to test the performance of a [Django Admin action](https://docs.djangoproject.com/en/1.8/ref/contrib/admin/actions/).

When I load the admin page, the Django Debug Toolbar shows 15 SQL queries. After I run the action, it still shows 15 SQL queries. I know my action ran, so the SQL queries in the action are not being profiled.

How can I profile a Django Admin action? Thanks.

**Comment by aaugustin** [comment]
That's because of the POST-redirect-GET pattern. It isn't specific to admin actions. You'd have the same effect on any view. Use the intercept redirect feature of the debug toolbar to monitor what happens on the POST rather than the subsequent GET.

**Comment by TravisDart** [comment]
I see. I was able to profile the Admin action when using "Intercept redirects".
