### ISSUE TITLE
TypeError with GzipMiddleware

### ISSUE THREAD

**Issue by Chronial** [django-debug-toolbar/django-debug-toolbar#787]
If the toolbar middleware is not set up and settings patching is disabled (e.g. because `DEBUG` is `False`), the following exception is thrown:
```
TypeError: unorderable types: NoneType() < int()

  File "manage.py", line 11, in <module>
    django.setup()
  File "django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "debug_toolbar/apps.py", line 16, in ready
    dt_settings.check_middleware()
  File "debug_toolbar/settings.py", line 169, in check_middleware
    if gzip_index is not None and debug_toolbar_index < gzip_index:
```

The `debug_tooblar_index` is `None`, as the toolbar is not set up. This is not checked.

**Comment by aaugustin** [comment]
I'm not convinced that it's a valid setup to have `'debug_toolbar'` in `INSTALLED_APPS` but not its middleware in `MIDDLEWARE_CLASSES`. What's the use case for that?

**Comment by Chronial** [comment]
That's what's recommended in the documentation: http://django-debug-toolbar.readthedocs.org/en/latest/installation.html#quick-setup

Adding gzip to that and setting `DEBUG` to `False` will cause the exception.

**Comment by Chronial** [comment]
Aaaand just read on for a little bit and found the notice:

> When the automatic setup is used, the Debug Toolbar is not compatible with GZipMiddleware. Please disable that middleware during development or use the explicit setup to allow the toolbar to function properly.

But thinking about it, this is not clear either – disabling gzip when `DEBUG` is set will not avoid this issue.

This is at least a documentation error and the exception raised is very much not helpful :).

**Comment by aaugustin** [comment]
I'm opposed to the automatic setup on philosophical grounds :-) In practice it turns out that it doesn't work for many people. I'm merely keeping it for legacy reasons. I think everyone should be using the explicit setup.

**Comment by Chronial** [comment]
That does sound very reasonable to me, but note that the documentation gives the opposite impression. It mentions the automatic setup first and the explicit setup seems more of an afterthought.

The next page starts with this notice:

> Do you really need a customized configuration?
> 
> The debug toolbar ships with a default configuration that is considered sane for the vast majority of Django projects. Don’t copy-paste blindly the default values shown below into you settings module! It’s useless and it’ll prevent you from taking advantage of better defaults that may be introduced in future releases.

I assume this is actually only meant to apply to the internal debug toolbar settings, but is easily mistaken to a notice about automatic setup.

I remember reading the docu and thinking "well, this automatic setup seems weird and hackish, but if it's the recommended way, I guess I'll go with it". If you want people to not use that, you should restructure the docu and clearly say that it's deprecated.

But I think this issue is still a bug. If you think having the toolbar in installed apps and not as a middleware, you should throw an exception that says that this is an invalid config.

```python
if debug_toolbar_index is None:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured("debug_toolbar is listed in INSTALLED_APPS, but the middleware is not installed. This configuration is not supported")
```

**Comment by aaugustin** [comment]
I'm not the sole decision taker here :-)

**Comment by aaugustin** [comment]
The discussion above looks like this is a documentation issue. I'm not sure what the best way forwards is.

In general I think it's more useful to document configs that make sense than to silently ignore configs that don't.

**Comment by aaugustin** [comment]
I clarified my opinion about the automatic setup in 833147237454a908ab2f83b4b976853de3194a86.

However this doesn't address all of the OP's points, so I'm leaving this issue open.

**Comment by Chronial** [comment]
:+1: That solves the issue for me – if the documentation would have been like that, I would have not run into this problem :).

**Comment by aaugustin** [comment]
Let's leave it there, then.

I'm sorry I took so long to get around to improving the docs.

Thanks and let us know if you have further suggestions.

**Comment by edmorley** [comment]
> I clarified my opinion about the automatic setup in 8331472.

Would it be possible to make sure that docs update appears on the default installation docs page?

Currently visiting http://django-debug-toolbar.readthedocs.io/ takes you to the 1.4 tag docs, which don't include the corrected steps. This caused a bit of confusion for us today along the lines of the OP here :-)
