### ISSUE TITLE
v1.4 forcing upgrade to django1.9 in PyCharm virtualenv

### ISSUE THREAD

**Issue by richardbrockie** [django-debug-toolbar/django-debug-toolbar#795]
Hi,
I'm using virtualenvs managed in PyCharm. I have a django v1.8.x (LTS) project that will follow the LTS versions. Only debug-toolbar v1.4 is available from repository https://pypi.python.org/pypi. However, when I upgrade from the existing debug-toolbar 1.2.2 to 1.4, my django installation is forced to become v1.9.

**Comment by aaugustin** [comment]
That's weird because `setup.py` only requires Django >= 1.7.

**Comment by GoTop** [comment]
I got the same problem too

**Comment by richardbrockie** [comment]
I was attempting to upgrade from v1.2.2. While upgrading to v1.4 still causes django to roll to v1.9, I finally worked out that uninstalling and then installing django-debug-toolbar does not roll django forward.

**Comment by jgbishop** [comment]
I also ran into this issue this morning, though in a different virtual environment. Could the `sqlparse` requirement (or one of its dependencies) be responsible? I was able to revert back to 1.8.11 (in my case), and then re-install the Django debug toolbar (1.4).
