### ISSUE TITLE
jQuery for offline development

### ISSUE THREAD

**Issue by kissgyorgy** [django-debug-toolbar/django-debug-toolbar#803]
My internet connection went off, so the default of getting jQuery from cdn slowed the load time for the pages so much that I couldn't develop and had to turn debug-toolbar off.
The problem with this is when I first encountered it, I couldn't look up the solution in the documentation, so I did not know about the `JQUERY_URL` setting :smile:

My suggestion is to vendor jQuery, make a fallback to local copy and get rid of the `JQUERY_URL` setting.

**Comment by aaugustin** [comment]
I introduced the `JQUERY_URL` setting and removed the vendored copy of jQuery because it made the vast majority of the size of the package, which felt wrong.

**Comment by kissgyorgy** [comment]
Ok then :smile:

**Comment by maikelvl** [comment]
@aaugustin I agree bundling jQuery feels wrong. Would you accept a PR where jQuery is fetched and stored locally in post installation?
