### ISSUE TITLE
Pages take long time to load after adding django-debug-toolbar

### ISSUE THREAD

**Issue by davneet4u** [django-debug-toolbar/django-debug-toolbar#806]
After adding `django-debug-toolbar` , my pages (all of them) load after a lot of time, more than 5 mins. And if it does not load, it gives `error: [Errno 32] Broken pipe.`

I am using Django 1.7, django-debug-toolbar 1.4.

**Comment by bradshjg** [comment]
You should try removing panels in order to find which the offender is. I've seen this several times, in one case someone was vendoring a bunch of js libraries (including all of the documentation) and had 50,000+ static files. See https://django-debug-toolbar.readthedocs.org/en/1.4/configuration.html#debug-toolbar-panels for the different panels.

**Comment by aaugustin** [comment]
This looks similar to #517.

**Comment by davneet4u** [comment]
@bradshjg I added the panels https://django-debug-toolbar.readthedocs.org/en/1.4/configuration.html#debug-toolbar-panels in my settings and tried to remove them one by one. It does not make a difference.

@aaugustin I don't know how #517 solves my issue. Am I missing something?

**Comment by aaugustin** [comment]
I don't know either. I was pointing out that the syndroms look similar but that doesn't imply a common cause. I didn't check if the fix for #517 is included in 1.4; if not, it could be a duplicate.

**Comment by davneet4u** [comment]
@aaugustin It was merged in 1.4

**Comment by bradshjg** [comment]
@davneet4u Have you figured this out yet?

If not, I don't mind taking a look at the project if you have a link to the source and seeing if anything sticks out.

**Comment by davneet4u** [comment]
@bradshjg I need to figure out if it is caused by something else, will confirm if it an issue of debug-toolbar.

**Comment by davneet4u** [comment]
The problem was that I was using `django-pipeline` & it took a huge time to load on local. If I do  `**PIPELINE_ENABLED** = True,` everything works fine.
