### ISSUE TITLE
Support for Jinja2 templates

### ISSUE THREAD

**Issue by chris-erickson** [django-debug-toolbar/django-debug-toolbar#810]
Is it planned to support Jinja2 templates?  Template context is a huge part of why I love DDT, and with Jinja2 template support in Django not working with Jinja2 templates, I'm sad.

**Comment by aaugustin** [comment]
It's "planned" in the sense that a good patch would certainly be accepted but not in the sense that anyone is working on it. (It isn't like anyone is maintaining the debug toolbar anyway.) This idea is currently tracked in #693.
