### ISSUE TITLE
system hang with Django 1.7.11 debug toolbar 1.4 Python2.7

### ISSUE THREAD

**Issue by professorDante** [django-debug-toolbar/django-debug-toolbar#812]
With this configuration, adding 'debug_toolbar' to apps, and then starting server causes server to hang indefintely with this stack trace:

/Users/ricko/Documents/Krome/Django/virtual_envs/gorilla_trade/lib/python2.7/site-packages/app_plugins/forms.py:16: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form AdminPluginPointForm needs updating
  class AdminPluginPointForm(forms.ModelForm):

/Users/ricko/Documents/Krome/Django/virtual_envs/gorilla_trade/lib/python2.7/site-packages/app_plugins/forms.py:24: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form AdminPluginForm needs updating
  class AdminPluginForm(forms.ModelForm):

/Users/ricko/Documents/Krome/Django/virtual_envs/gorilla_trade/lib/python2.7/site-packages/Satchmo-0.9.3-py2.7.egg/satchmo_utils/admin.py:162: RemovedInDjango18Warning: Options.module_name has been deprecated in favor of model_name
  model_name = self.model._meta.module_name

/Users/ricko/Documents/Krome/Django/virtual_envs/gorilla_trade/lib/python2.7/site-packages/reversion/admin.py:136: RemovedInDjango18Warning: Options.module_name has been deprecated in favor of model_name
  info = opts.app_label, opts.module_name,

Removing debug toolbar from apps fixes the issue.

**Comment by aaugustin** [comment]
This is a known problem of the implicit, auto-magic setup. Sorry about that. Please use the explicit setup. See the documentation for details.

**Comment by ghedsouza** [comment]
@aaugustin Could you please provide more details? I've gone through the setup instructions in the docs and have the same problem. What should I change exactly?

**Comment by matthiask** [comment]
You should start by using supported versions of Django. 1.8 was a LTS, but isn't supported anymore. 1.11 is the oldest still supported version of Django.
