### ISSUE TITLE
Empty JQUERY_URL being ignored?

### ISSUE THREAD

**Issue by maltebeckmann** [django-debug-toolbar/django-debug-toolbar#814]
Hi, 

I left the JQUERY_URL empty. But the toolbar is still trying to connect to the Google hosted file. Are my Toolbar settings incorrectly formatted?

CONFIG_DEFAULTS = {
    'JQUERY_URL': '',
}

DEBUG_TOOLBAR_PATCH_SETTINGS = False

**Comment by aaugustin** [comment]
The setting is called `DEBUG_TOOLBAR_CONFIG`, not `CONFIG_DEFAULTS`.

**Comment by maltebeckmann** [comment]
Sigh. Thanks!!

**Comment by maltebeckmann** [comment]
Sigh. Thanks!!
