### ISSUE TITLE
jquery.min.js net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by 510908220** [django-debug-toolbar/django-debug-toolbar#815]
in china, i cannot visit http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js, so debug-tool-bar can not use.

**Comment by aaugustin** [comment]
Please use the `JQUERY_URL` configuration option. See the documentation for details.

**Comment by 510908220** [comment]
ok. i change it  in my local .
