### ISSUE TITLE
Stand alone SQL trace

### ISSUE THREAD

**Issue by btoueg** [django-debug-toolbar/django-debug-toolbar#817]
I find very handy the SQL pPanel:
 - I can see where are the heavy queries
 - I can find instantly what queryset is causing which query

I'd like to have the benefits of these visualisation when I am running CLI unit tests, thus having the benefits of the SQL Panel as a stand-alone.

Has anyone done that?

**Comment by aaugustin** [comment]
Django has this feature is built-in: `django-admin test --debug-sql`
