### ISSUE TITLE
v1.4 forces upgrade to Django==1.9.5

### ISSUE THREAD

**Issue by halfnibble** [django-debug-toolbar/django-debug-toolbar#818]
Not sure if this is intentional, but using `pip install --upgrade django-debug-toolbar` with a Django 1.8.11 install causes Django to be upgraded to 1.9.5.

**Comment by aaugustin** [comment]
I think we fixed that. Could you search for an earlier ticket about this issue?

**Comment by ad-m** [comment]
@aaugustin , see #795, #766.

**Comment by aaugustin** [comment]
Yes that's my point. There was a resolution to these tickets.

**Comment by ad-m** [comment]
See caioariede/django-location-field#47, django-guardian/django-guardian#423, charettes/django-admin-enhancer#23, carljm/django-model-utils#183 for similiar issues.

```
$ pipdeptree 
pkg-resources==0.0.0
wheel==0.29.0
argparse==1.2.1
wsgiref==0.1.2
django-debug-toolbar==1.4
  - Django [required: >=1.7, installed: 1.9.6]
  - sqlparse [installed: 0.1.19]
tox==2.3.1
  - py [required: >=1.4.17, installed: 1.4.31]
  - virtualenv [required: >=1.11.2, installed: 15.0.1]
  - pluggy [required: <0.4.0,>=0.3.0, installed: 0.3.1]`
```

**Comment by halfnibble** [comment]
Interesting. There was another package that I installed that did the same thing. This is quite possibly not a django-debug-toolbar bug, but rather a dependency bug. Or pip bug?

**Comment by ad-m** [comment]
I created issues pypa/pi#3653 to verify potential pip bug.

**Comment by aaugustin** [comment]
As far as I can tell, this is a discussion about the behavior of pip, not the behavior of the toolbar.
