### ISSUE TITLE
setup documentation recommends using deprecated function

### ISSUE THREAD

**Issue by adriannye** [django-debug-toolbar/django-debug-toolbar#820]
The documentation says to insert the following in the project urls.py:

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

But the patterns function is deprecated since django 1.8:

https://docs.djangoproject.com/en/1.9/ref/urls/

Now urlpatterns is supposed to be a simple list of url() instances so it should be:

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

**Comment by aaugustin** [comment]
I fixed this some time ago in c2658d13df4f8479ef356597680a62716c60ee61.
