### ISSUE TITLE
There is no 'south' database module

### ISSUE THREAD

**Issue by priya124** [django-debug-toolbar/django-debug-toolbar#824]
I am having Django 1.9.6 and django-two-factor-auth==1.3.1
Now i am getting this error..
Please help me to solve this error.

./manage.py syncdb --noinput
There is no South database module 'south.db.sqlite3' for your database. Please either choose a supported database, check for SOUTH_DATABASE_ADAPTER[S] settings, or remove South from INSTALLED_APPS

**Comment by priya124** [comment]
if i removed or unistall south it will say
ImportError: No module named south 
so please give me a solution

**Comment by tim-schilling** [comment]
If you're using Django 1.9, you don't need to be using south. Remove it from your `INSTALLED_APPS` in your settings. Also, this repo is for the django debug toolbar. You will be better off asking questions similar to this on StackOverflow.

**Comment by priya124** [comment]
Thank you for replying
