### ISSUE TITLE
There is no South database module 'south.db.sqlite3' for your database.

### ISSUE THREAD

**Issue by priya124** [django-debug-toolbar/django-debug-toolbar#825]
Please help me to solve this issue

sudo python manage.py createdb
There is no South database module 'south.db.sqlite3' for your database. Please either choose a supported database, check for SOUTH_DATABASE_ADAPTER[S] settings, or remove South from INSTALLED_APP

**Comment by tim-schilling** [comment]
Closing as a duplicate of #824

**Comment by aaugustin** [comment]
@priya124 Please stop spamming this bug tracker with unrelated problems. I will close any further issue without comment. Sorry.
