### ISSUE TITLE
Im not able to see the toolbar on the test server (AWS Elastic Beanstalk) but its available on the local server !!!

### ISSUE THREAD

**Issue by guganselvaraj** [django-debug-toolbar/django-debug-toolbar#839]
Hi,

I have installed and configured for the DJDT , but im not able to see the tool bar in my test server !!!???

is there anything else i need to do for it , to make it work on the test / production server???

**Comment by aaugustin** [comment]
As described in the documentation, there are additional controls to avoid accidentally exposing the debug info on the Internet. Look at SHOW_TOOLBAR_CALLBACK.
