### ISSUE TITLE
Appears to be incompatible with sqlparse version 0.2.0.

### ISSUE THREAD

**Issue by mlockett42** [django-debug-toolbar/django-debug-toolbar#852]
I get the following exception and stack trace on every page I try to view:

```
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  223.                 response = middleware_method(request, response)
File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/middleware.py" in process_response
  129.                 panel.generate_stats(request, response)
File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/panels/sql/panel.py" in generate_stats
  192.                     query['sql'] = reformat_sql(query['sql'])
File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/panels/sql/utils.py" in reformat_sql
  27.     return swap_fields(''.join(stack.run(sql)))
File "/usr/local/lib/python2.7/dist-packages/sqlparse/engine/filter_stack.py" in run
  29.             stream = filter_.process(stream)

Exception Type: TypeError at /admin/mediasources/document/
Exception Value: process() takes exactly 3 arguments (2 given)

```

I can workaround by forcing the version to 0.1.19 via 
sqlparse==0.1.19
in the requirements file.

sqlparse 0.2.0 was released today

**Comment by aaugustin** [comment]
If someone feels like investigating how to update the DDT to work with sqlparse 0.2.0 that would be even better :-)

**Comment by gabber7** [comment]
the changed the api of filters, the stack-parameter does not exist in version 0.2.0, see
https://github.com/django-debug-toolbar/django-debug-toolbar/blob/master/debug_toolbar/panels/sql/utils.py#L12

**Comment by tctimmeh** [comment]
+1. Upgrading my dev site today with DDT enabled made the site suddenly unusable.

**Comment by dirtycoder** [comment]
well, that's funny haha xD

**Comment by valentjedi** [comment]
@dirtycoder you was the first though :)

**Comment by browniebroke** [comment]
Maybe also update minimum version of sqlparse>=0.2.0 in [setup.py](https://github.com/django-debug-toolbar/django-debug-toolbar/blob/master/setup.py#L19)?

**Comment by valentjedi** [comment]
@browniebroke good idea since it won't work with an old version anymore. I've updated PR accordingly.

**Comment by dirtycoder** [comment]
I don't see much sense in both of us doing the same stuff over and over so I'll close my PR.

**Comment by andialbrecht** [comment]
Sorry guys, I've forgot to mention this change in the release notes for sqlparse ;)
