### ISSUE TITLE
SQLPARSE now could crash whole application

### ISSUE THREAD

**Issue by pypetey** [django-debug-toolbar/django-debug-toolbar#857]
Hi

Could you please do an update for sqlparse? New version was released and it's incompatible with current version of django debug toolbar. Which means that if someone does a clean install of DDT then upon running a server you will get an error with sqlparse.

**Comment by aaugustin** [comment]
I made a release to address this issue about 90 minutes before you filed :-)

Please reopen if the problem persists with version 1.5.
