### ISSUE TITLE
TypeError: process() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by narrowfail** [django-debug-toolbar/django-debug-toolbar#862]
Hello, had to shut down django-debug-toolbar due this error:

```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/core/model/list/

Django Version: 1.9.7
Python Version: 2.7.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'debug_toolbar',
 'django_countries',
 'sorl.thumbnail',
 'rest_framework',
 'widget_tweaks',
 'bootstrap_pagination',
 'apps.core',
 'apps.users',
 'apps.landing']
Installed Middleware:
[u'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware']



Traceback:

File "/dir/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  235.                 response = middleware_method(request, response)

File "/dir/venv/local/lib/python2.7/site-packages/debug_toolbar/middleware.py" in process_response
  129.                 panel.generate_stats(request, response)

File "/dir/venv/local/lib/python2.7/site-packages/debug_toolbar/panels/sql/panel.py" in generate_stats
  192.                     query['sql'] = reformat_sql(query['sql'])

File "/dir/venv/local/lib/python2.7/site-packages/debug_toolbar/panels/sql/utils.py" in reformat_sql
  27.     return swap_fields(''.join(stack.run(sql)))

File "/dir/venv/local/lib/python2.7/site-packages/sqlparse/engine/filter_stack.py" in run
  29.             stream = filter_.process(stream)

Exception Type: TypeError at /core/model/list/
Exception Value: process() takes exactly 3 arguments (2 given)
```

PIP:
```
Django==1.9.7
django-bootstrap-pagination==1.6.1
django-countries==3.4.1
django-debug-toolbar==1.4
django-filter==0.13.0
django-widget-tweaks==1.4.1
djangorestframework==3.4.0
Markdown==2.6.6
Pillow==3.3.0
PyMySQL==0.7.5
sorl-thumbnail==12.3
sqlparse==0.2.0
wheel==0.24.0

```

**Comment by aaugustin** [comment]
Upgrade the debug toolbar to 1.5 or downgrade sqlparse to 0.1.x.

There's a bunch of duplicates of this ticket if you need more info.

**Comment by narrowfail** [comment]
Thanks!

**Comment by deriensk** [comment]
Similar error,
TypeError: process() takes exactly 3 arguments (2 given)
for the installation of django booktype

pip freeze
---------------------------------------------
alabaster==0.7.10
amqp==1.4.9
anyjson==0.3.3
Babel==2.5.1
billiard==3.3.0.23
celery==3.1.0
certifi==2017.11.5
chardet==3.0.4
Django==1.7.8
django-appconf==1.0.2
django-braces==1.12.0
django-celery==3.1.16
django-compressor==1.5
django-debug-toolbar==1.3.0
-e git://github.com/dcramer/django-devserver.git@35f9abf601e6cc2ed3cdbb78fb60018d7bd5a48d#egg=django_devserver
django-discover-runner==1.0
django-redis==4.8.0
docutils==0.14
-e git://github.com/aerkalov/ebooklib.git@7f208133103455af78443d97a5219b700071971c#egg=EbookLib
factory-boy==2.9.2
Faker==0.8.8
funcsigs==1.0.2
idna==2.6
imagesize==0.7.1
ipaddress==1.0.19
Jinja2==2.10
kombu==3.0.37
lxml==4.1.1
MarkupSafe==1.0
mock==2.0.0
pbr==3.1.1
pep8==1.7.1
pika==0.11.2
Pillow==2.9.0
pkg-resources==0.0.0
Pygments==2.2.0
python-dateutil==2.6.1
Python-OOXML==0.13
pytz==2017.3
redis==2.10.6
requests==2.18.4
selenium==3.8.0
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.6.5
sphinxcontrib-websupport==1.0.1
sqlparse==0.2.4
text-unidecode==1.1
timeutils==0.3.2
typing==3.6.2
Unidecode==0.4.21
Unipath==1.1
urllib3==1.22
vine==1.1.4
